name: Build, Scan with SonarCloud, and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Améliore la pertinence du reporting

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: "-Xmx1024m"  # Optionnel, ajuste la mémoire utilisée par le scanner
      with:
        args: >
          -Dsonar.organization=enzovilla10
          -Dsonar.projectKey=enzovilla10_cd
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=./tp1  # Adaptez cette ligne si les sources sont dans un autre dossier
          -Dsonar.exclusions=**/tests/**  # Exclure les tests si nécessaire
          
  build:
    runs-on: ubuntu-latest
    needs: sonarcloud  # Ce job attend la fin du job SonarCloud
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./tp1 
        file: ./tp1/Dockerfile
        push: true
        tags: |
          enzo10villa/cd:latest
          enzo10villa/cd:${{ github.sha }}
