name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./tp1  
        file: ./tp1/Dockerfile
        push: true
        tags: |
          enzo10villa/cd:latest
          enzo10villa/cd:${{ github.sha }}

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        organization: ${{ secrets.enzo10villa }}
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Run SonarCloud Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=<your_project_key> \
          -Dsonar.organization=${{ secrets.enzo10villa }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
