name: Build App

on:
    push:
        branches:
        - main  # Si votre branche par défaut est 'master', remplacez 'main' par 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: <your-dockerhub-username>/cd
            tag_with_sha: true
